version: "3.0"

services:
  elasticsearch:
    image:  docker.elastic.co/elasticsearch/elasticsearch:5.6.3 
    container_name: elasticsearch
    volumes:
    - ./config/elastic.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300" 
    environment:
      transport.host: "0.0.0.0"
      http.host: "0.0.0.0"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m" 
    networks:
      - elastic

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:5.6.3
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elastic
        
networks:
  elastic:
    driver: bridge

