
version: "3.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.0
    container_name: test_elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      transport.host: "0.0.0.0"
      http.host: "0.0.0.0"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      cluster.name: "test_elastic"
      network.host: "0.0.0.0"
      discovery.zen.minimum_master_nodes: "1"
      discovery.type: "single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  kibana:
      depends_on:
        - elasticsearch
      image: docker.elastic.co/kibana/kibana-oss:6.4.0
      container_name: test_kibana
      environment:
        SERVER_NAME: kibananananana
        ELASTICSEARCH_URL: http://elasticsearch:9200
      ports:
        - "5601:5601"
      networks:
        - elastic
networks:
  elastic:
    driver: bridge