version: "3.0"

services:
  elastic:
    image:  docker.elastic.co/elasticsearch/elasticsearch:5.5.3 
    container_name: elastic
    ports:
      - "9200:9200"
      - "9300:9300" 
    environment:
      - "discovery.type=single-node" 
      - "xpack.security.enabled=false"

